### PR TITLE
Added UCL CS Discord server link.

### PR DESCRIPTION
**Pull request by TheRootOf3**
This PR introduces a UCL CS Discord Server link to the website. 
The website builds.

Preview:
image

### CODE REVIEW

**Comment by Foalfloater66** [comment]
Had a look. Do you want to update the announcement to emphasise the link's existence? This change is tough to notice, since it's so small.

**Comment by Foalfloater66** [comment]
Yarn's build system reported a broken link during my local build. It must have been on my end. I've fixed it, but just remember to rebase your work now that the `main` branch has changed.

**Review by Foalfloater66 — APPROVED** [review]
Everything here is good. I would recommend adding this new feature as an announcement since the change is tough to notice, but it's not a deal-breaker.

(Remember to rebase & merge since `main` has some changes.

**Comment by TheRootOf3** [comment]
> Everything here is good. I would recommend adding this new feature as an announcement since the change is tough to notice, but it's not a deal-breaker.

Good idea! Adding to the announcement bar!

**Comment by TheRootOf3** [comment]
Added: 
image

**Pull request merged**
